services:
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
      - "8001:8001"

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - "/qdrant_storage:/qdrant_storage:z"

  worker:
    build: .
    depends_on:
      - redis
    command: node worker.js

  app:
    build: .
    environment:
      - QDRANT_SERVER_URL=${QDRANT_SERVER_URL}
      - UNSTRUCTURED_API_KEY=${UNSTRUCTURED_API_KEY}
      - UNSTRUCTURED_API_URL=${UNSTRUCTURED_API_URL}
      - LM_STUDIOS_SERVER_URL=${LM_STUDIOS_SERVER_URL}
      - HOST=redis
    depends_on:
      - redis
      - qdrant
    command: node app.js